name: My Workflow

on:
  push:
    branches:
      - main





jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v3 


      - name: 'After'
        run: ls
