name: My Workflow

on:
  push:
    branches:
      - main





jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3 


      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }}  --password ${{ secrets.DOCKER_TOKEN }}


      - name: "Building docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test1 . 


      - name: "pushing to Docker hub"
        run: docker push  ${{ secrets.DOCKER_USERNAME }}/test1