name: My Workflow
on:
  push:
    branches:
      - main





jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
      - name: 'Testing github action'
        run: pwd


      - name: 'Testing printing'
        run: echo eyad
